//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 05:27:36 PM CET 
//


package zalbacutanje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.zalba package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.zalba
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zalbacutanje }
     * 
     */
    public Zalbacutanje createZalbacutanje() {
        return new Zalbacutanje();
    }

    /**
     * Create an instance of {@link Zalbacutanje.DetaljiPredaje }
     * 
     */
    public Zalbacutanje.DetaljiPredaje createZalbacutanjeDetaljiPredaje() {
        return new Zalbacutanje.DetaljiPredaje();
    }

    /**
     * Create an instance of {@link Zalbacutanje.InformacijeOPodnosiocuZalbe }
     * 
     */
    public Zalbacutanje.InformacijeOPodnosiocuZalbe createZalbacutanjeInformacijeOPodnosiocuZalbe() {
        return new Zalbacutanje.InformacijeOPodnosiocuZalbe();
    }

}
