//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 10:52:21 AM CET 
//


package com.administration.services.dto.odgovor;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public OdgovorSluzbenika createOdgovorSluzbenika() {
        return new OdgovorSluzbenika();
    }

    public Odgovori createOdgovori() {
        return new Odgovori();
    }

}
