//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 10:52:21 AM CET 
//


package com.administration.services.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.administration.services.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.administration.services.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link Resenje }
     *
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link Zahtev }
     *
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link Zalbacutanje }
     *
     */
    public Zalbacutanje createZalbacutanje() {
        return new Zalbacutanje();
    }

    /**
     * Create an instance of {@link Zalbanaodluku }
     *
     */
    public Zalbanaodluku createZalbanaodluku() {
        return new Zalbanaodluku();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.DetaljiPredaje }
     *
     */
    public Zalbanaodluku.DetaljiPredaje createZalbanaodlukuDetaljiPredaje() {
        return new Zalbanaodluku.DetaljiPredaje();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.Resenje }
     *
     */
    public Zalbanaodluku.Resenje createZalbanaodlukuResenje() {
        return new Zalbanaodluku.Resenje();
    }

    /**
     * Create an instance of {@link Zalbacutanje.DetaljiPredaje }
     *
     */
    public Zalbacutanje.DetaljiPredaje createZalbacutanjeDetaljiPredaje() {
        return new Zalbacutanje.DetaljiPredaje();
    }

    /**
     * Create an instance of {@link Zahtev.DetaljiPredaje }
     *
     */
    public Zahtev.DetaljiPredaje createZahtevDetaljiPredaje() {
        return new Zahtev.DetaljiPredaje();
    }

    /**
     * Create an instance of {@link Zahtev.Organ }
     *
     */
    public Zahtev.Organ createZahtevOrgan() {
        return new Zahtev.Organ();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja }
     *
     */
    public Resenje.TeloResenja createResenjeTeloResenja() {
        return new Resenje.TeloResenja();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja.UpravniSpor }
     *
     */
    public Resenje.TeloResenja.UpravniSpor createResenjeTeloResenjaUpravniSpor() {
        return new Resenje.TeloResenja.UpravniSpor();
    }

    /**
     * Create an instance of {@link Resenje.Zaglavlje }
     *
     */
    public Resenje.Zaglavlje createResenjeZaglavlje() {
        return new Resenje.Zaglavlje();
    }

    /**
     * Create an instance of {@link Resenje.Zaglavlje.InformacijePredmeta }
     *
     */
    public Resenje.Zaglavlje.InformacijePredmeta createResenjeZaglavljeInformacijePredmeta() {
        return new Resenje.Zaglavlje.InformacijePredmeta();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo }
     *
     */
    public Obavestenje.Telo createObavestenjeTelo() {
        return new Obavestenje.Telo();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid }
     *
     */
    public Obavestenje.Telo.Uvid createObavestenjeTeloUvid() {
        return new Obavestenje.Telo.Uvid();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid.Vreme }
     *
     */
    public Obavestenje.Telo.Uvid.Vreme createObavestenjeTeloUvidVreme() {
        return new Obavestenje.Telo.Uvid.Vreme();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.TrazenaInformacija }
     *
     */
    public Obavestenje.Telo.TrazenaInformacija createObavestenjeTeloTrazenaInformacija() {
        return new Obavestenje.Telo.TrazenaInformacija();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje }
     *
     */
    public Obavestenje.Zaglavlje createObavestenjeZaglavlje() {
        return new Obavestenje.Zaglavlje();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje.Organ }
     *
     */
    public Obavestenje.Zaglavlje.Organ createObavestenjeZaglavljeOrgan() {
        return new Obavestenje.Zaglavlje.Organ();
    }

    /**
     * Create an instance of {@link Izvestaj.Zalbe }
     *
     */
    public Izvestaj.Zalbe createIzvestajZalbe() {
        return new Izvestaj.Zalbe();
    }

    /**
     * Create an instance of {@link Izvestaji }
     *
     */
    public Izvestaji createIzvestaji() {
        return new Izvestaji();
    }

    /**
     * Create an instance of {@link Izvestaj.Podnosilac }
     *
     */
    public Izvestaj.Podnosilac createIzvestajPodnosilac() {
        return new Izvestaj.Podnosilac();
    }

    /**
     * Create an instance of {@link Izvestaj.DatumPodnosenja }
     *
     */
    public Izvestaj.DatumPodnosenja createIzvestajDatumPodnosenja() {
        return new Izvestaj.DatumPodnosenja();
    }

    /**
     * Create an instance of {@link Izvestaj.Zahtevi }
     *
     */
    public Izvestaj.Zahtevi createIzvestajZahtevi() {
        return new Izvestaj.Zahtevi();
    }

    /**
     * Create an instance of {@link Tosoba }
     *
     */
    public Tosoba createTosoba() {
        return new Tosoba();
    }

    /**
     * Create an instance of {@link Korisnici }
     *
     */
    public Korisnici createKorisnici() {
        return new Korisnici();
    }

    /**
     * Create an instance of {@link Korisnik.EmailAdresa }
     *
     */
    public Korisnik.EmailAdresa createKorisnikEmailAdresa() {
        return new Korisnik.EmailAdresa();
    }

    /**
     * Create an instance of {@link Obavestenja }
     *
     */
    public Obavestenja createObavestenja() {
        return new Obavestenja();
    }

    /**
     * Create an instance of {@link Resenja }
     *
     */
    public Resenja createResenja() {
        return new Resenja();
    }

    /**
     * Create an instance of {@link Resenje.RazlogZalbe }
     *
     */
    public Resenje.RazlogZalbe createResenjeRazlogZalbe() {
        return new Resenje.RazlogZalbe();
    }

    /**
     * Create an instance of {@link Resenje.Poverenik }
     *
     */
    public Resenje.Poverenik createResenjePoverenik() {
        return new Resenje.Poverenik();
    }

    /**
     * Create an instance of {@link Zahtevi }
     *
     */
    public Zahtevi createZahtevi() {
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link Zahtev.Status }
     *
     */
    public Zahtev.Status createZahtevStatus() {
        return new Zahtev.Status();
    }

    /**
     * Create an instance of {@link Zahtev.ListaZahteva }
     *
     */
    public Zahtev.ListaZahteva createZahtevListaZahteva() {
        return new Zahtev.ListaZahteva();
    }

    /**
     * Create an instance of {@link Zahtev.InformacijeOTraziocu }
     *
     */
    public Zahtev.InformacijeOTraziocu createZahtevInformacijeOTraziocu() {
        return new Zahtev.InformacijeOTraziocu();
    }

    /**
     * Create an instance of {@link Zalbecutanje }
     *
     */
    public Zalbecutanje createZalbecutanje() {
        return new Zalbecutanje();
    }

    /**
     * Create an instance of {@link Zalbacutanje.Status }
     *
     */
    public Zalbacutanje.Status createZalbacutanjeStatus() {
        return new Zalbacutanje.Status();
    }

    /**
     * Create an instance of {@link Zalbacutanje.NazivOrgana }
     *
     */
    public Zalbacutanje.NazivOrgana createZalbacutanjeNazivOrgana() {
        return new Zalbacutanje.NazivOrgana();
    }

    /**
     * Create an instance of {@link Zalbacutanje.InformacijeOPodnosiocuZalbe }
     *
     */
    public Zalbacutanje.InformacijeOPodnosiocuZalbe createZalbacutanjeInformacijeOPodnosiocuZalbe() {
        return new Zalbacutanje.InformacijeOPodnosiocuZalbe();
    }

    /**
     * Create an instance of {@link Zalbenaodluku }
     *
     */
    public Zalbenaodluku createZalbenaodluku() {
        return new Zalbenaodluku();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.Status }
     *
     */
    public Zalbanaodluku.Status createZalbanaodlukuStatus() {
        return new Zalbanaodluku.Status();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.PodnosilacZalbe }
     *
     */
    public Zalbanaodluku.PodnosilacZalbe createZalbanaodlukuPodnosilacZalbe() {
        return new Zalbanaodluku.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.NazivOrgana }
     *
     */
    public Zalbanaodluku.NazivOrgana createZalbanaodlukuNazivOrgana() {
        return new Zalbanaodluku.NazivOrgana();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.DatumPodnosenjaZahteva }
     *
     */
    public Zalbanaodluku.DatumPodnosenjaZahteva createZalbanaodlukuDatumPodnosenjaZahteva() {
        return new Zalbanaodluku.DatumPodnosenjaZahteva();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.InformacijeOPodnosiocuZalbe }
     *
     */
    public Zalbanaodluku.InformacijeOPodnosiocuZalbe createZalbanaodlukuInformacijeOPodnosiocuZalbe() {
        return new Zalbanaodluku.InformacijeOPodnosiocuZalbe();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.DetaljiPredaje.Mesto }
     *
     */
    public Zalbanaodluku.DetaljiPredaje.Mesto createZalbanaodlukuDetaljiPredajeMesto() {
        return new Zalbanaodluku.DetaljiPredaje.Mesto();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.DetaljiPredaje.Datum }
     *
     */
    public Zalbanaodluku.DetaljiPredaje.Datum createZalbanaodlukuDetaljiPredajeDatum() {
        return new Zalbanaodluku.DetaljiPredaje.Datum();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.Resenje.DatumResenja }
     *
     */
    public Zalbanaodluku.Resenje.DatumResenja createZalbanaodlukuResenjeDatumResenja() {
        return new Zalbanaodluku.Resenje.DatumResenja();
    }

    /**
     * Create an instance of {@link Zalbacutanje.DetaljiPredaje.Mesto }
     *
     */
    public Zalbacutanje.DetaljiPredaje.Mesto createZalbacutanjeDetaljiPredajeMesto() {
        return new Zalbacutanje.DetaljiPredaje.Mesto();
    }

    /**
     * Create an instance of {@link Zalbacutanje.DetaljiPredaje.Datum }
     *
     */
    public Zalbacutanje.DetaljiPredaje.Datum createZalbacutanjeDetaljiPredajeDatum() {
        return new Zalbacutanje.DetaljiPredaje.Datum();
    }

    /**
     * Create an instance of {@link Zahtev.DetaljiPredaje.Mesto }
     *
     */
    public Zahtev.DetaljiPredaje.Mesto createZahtevDetaljiPredajeMesto() {
        return new Zahtev.DetaljiPredaje.Mesto();
    }

    /**
     * Create an instance of {@link Zahtev.DetaljiPredaje.Datum }
     *
     */
    public Zahtev.DetaljiPredaje.Datum createZahtevDetaljiPredajeDatum() {
        return new Zahtev.DetaljiPredaje.Datum();
    }

    /**
     * Create an instance of {@link Zahtev.Organ.Sediste }
     *
     */
    public Zahtev.Organ.Sediste createZahtevOrganSediste() {
        return new Zahtev.Organ.Sediste();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja.Obrazlozenje }
     *
     */
    public Resenje.TeloResenja.Obrazlozenje createResenjeTeloResenjaObrazlozenje() {
        return new Resenje.TeloResenja.Obrazlozenje();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja.UpravniSpor.Mesto }
     *
     */
    public Resenje.TeloResenja.UpravniSpor.Mesto createResenjeTeloResenjaUpravniSporMesto() {
        return new Resenje.TeloResenja.UpravniSpor.Mesto();
    }

    /**
     * Create an instance of {@link Resenje.Zaglavlje.DatumResenja }
     *
     */
    public Resenje.Zaglavlje.DatumResenja createResenjeZaglavljeDatumResenja() {
        return new Resenje.Zaglavlje.DatumResenja();
    }

    /**
     * Create an instance of {@link Resenje.Zaglavlje.InformacijePredmeta.DatumPredmeta }
     *
     */
    public Resenje.Zaglavlje.InformacijePredmeta.DatumPredmeta createResenjeZaglavljeInformacijePredmetaDatumPredmeta() {
        return new Resenje.Zaglavlje.InformacijePredmeta.DatumPredmeta();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid.Adresa }
     * 
     */
    public Obavestenje.Telo.Uvid.Adresa createObavestenjeTeloUvidAdresa() {
        return new Obavestenje.Telo.Uvid.Adresa();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid.Vreme.Trajanje }
     * 
     */
    public Obavestenje.Telo.Uvid.Vreme.Trajanje createObavestenjeTeloUvidVremeTrajanje() {
        return new Obavestenje.Telo.Uvid.Vreme.Trajanje();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.TrazenaInformacija.DatumInformacija }
     * 
     */
    public Obavestenje.Telo.TrazenaInformacija.DatumInformacija createObavestenjeTeloTrazenaInformacijaDatumInformacija() {
        return new Obavestenje.Telo.TrazenaInformacija.DatumInformacija();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje.Datum }
     * 
     */
    public Obavestenje.Zaglavlje.Datum createObavestenjeZaglavljeDatum() {
        return new Obavestenje.Zaglavlje.Datum();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje.PodnosiocZahteva }
     * 
     */
    public Obavestenje.Zaglavlje.PodnosiocZahteva createObavestenjeZaglavljePodnosiocZahteva() {
        return new Obavestenje.Zaglavlje.PodnosiocZahteva();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje.Organ.SedisteOrgana }
     * 
     */
    public Obavestenje.Zaglavlje.Organ.SedisteOrgana createObavestenjeZaglavljeOrganSedisteOrgana() {
        return new Obavestenje.Zaglavlje.Organ.SedisteOrgana();
    }

    /**
     * Create an instance of {@link Izvestaj.Zalbe.NaOdluku }
     * 
     */
    public Izvestaj.Zalbe.NaOdluku createIzvestajZalbeNaOdluku() {
        return new Izvestaj.Zalbe.NaOdluku();
    }

    /**
     * Create an instance of {@link Izvestaj.Zalbe.Cutanje }
     * 
     */
    public Izvestaj.Zalbe.Cutanje createIzvestajZalbeCutanje() {
        return new Izvestaj.Zalbe.Cutanje();
    }

    /**
     * Create an instance of {@link Izvestaj.Zalbe.Spisak }
     * 
     */
    public Izvestaj.Zalbe.Spisak createIzvestajZalbeSpisak() {
        return new Izvestaj.Zalbe.Spisak();
    }

}
