//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 12:18:48 AM CET 
//


package com.administration.services.model;

import com.administration.services.configs.DateAdapter;
import com.administration.services.configs.YearMonthAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zaglavlje"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="rezultat_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="informacije_predmeta"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="broj_predmeta"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;pattern value="(\d{3}-\d{2}-\d{4})?"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="datum_predmeta"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://localhost:8080/tipovi&gt;TdatumBroj"&gt;
 *                                     &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="datum_resenja"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
 *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="razlog_zalbe"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="podnositelj_zalbe" type="{http://localhost:8080/tipovi}Tosoba"/&gt;
 *                   &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="telo_resenja"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="odgovor_na_zalbu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="obrazlozenje"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="uvod_obrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="postupajuci_po_zalbi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="dodatan_uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="odgovor_poverenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="upravni_spor"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="mesto"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="rok_prijema" type="{http://localhost:8080/tipovi}Trok"/&gt;
 *                             &lt;element name="taksa" type="{http://localhost:8080/tipovi}Ttrosak"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="poverenik"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://localhost:8080/tipovi}Tosoba"&gt;
 *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipResenje", propOrder = {
    "zaglavlje",
    "razlogZalbe",
    "teloResenja",
    "poverenik"
})
@XmlRootElement(name = "resenje")
public class Resenje {

    @XmlElement(required = true)
    protected Zaglavlje zaglavlje;
    @XmlElement(name = "razlog_zalbe", required = true)
    protected RazlogZalbe razlogZalbe;
    @XmlElement(name = "telo_resenja", required = true)
    protected TeloResenja teloResenja;
    @XmlElement(required = true)
    protected Poverenik poverenik;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "rel")
    @XmlSchemaType(name = "anySimpleType")
    protected String rel;
    @XmlAttribute(name = "href")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;
    @XmlAttribute(name = "vocab")
    @XmlSchemaType(name = "anySimpleType")
    protected String vocab;

    /**
     * Gets the value of the zaglavlje property.
     *
     * @return
     *     possible object is
     *     {@link Zaglavlje }
     *
     */
    public Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     *
     * @param value
     *     allowed object is
     *     {@link Zaglavlje }
     *
     */
    public void setZaglavlje(Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the razlogZalbe property.
     *
     * @return
     *     possible object is
     *     {@link RazlogZalbe }
     *
     */
    public RazlogZalbe getRazlogZalbe() {
        return razlogZalbe;
    }

    /**
     * Sets the value of the razlogZalbe property.
     *
     * @param value
     *     allowed object is
     *     {@link RazlogZalbe }
     *
     */
    public void setRazlogZalbe(RazlogZalbe value) {
        this.razlogZalbe = value;
    }

    /**
     * Gets the value of the teloResenja property.
     *
     * @return
     *     possible object is
     *     {@link TeloResenja }
     *
     */
    public TeloResenja getTeloResenja() {
        return teloResenja;
    }

    /**
     * Sets the value of the teloResenja property.
     *
     * @param value
     *     allowed object is
     *     {@link TeloResenja }
     *
     */
    public void setTeloResenja(TeloResenja value) {
        this.teloResenja = value;
    }

    /**
     * Gets the value of the poverenik property.
     *
     * @return
     *     possible object is
     *     {@link Poverenik }
     *
     */
    public Poverenik getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     *
     * @param value
     *     allowed object is
     *     {@link Poverenik }
     *
     */
    public void setPoverenik(Poverenik value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the rel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRel(String value) {
        this.rel = value;
    }

    /**
     * Gets the value of the href property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the vocab property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVocab(String value) {
        this.vocab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://localhost:8080/tipovi}Tosoba"&gt;
     *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Poverenik
        extends Tosoba
    {

        @XmlAttribute(name = "about")
        @XmlSchemaType(name = "anySimpleType")
        protected String about;
        @XmlAttribute(name = "rel")
        @XmlSchemaType(name = "anySimpleType")
        protected String rel;
        @XmlAttribute(name = "href")
        @XmlSchemaType(name = "anySimpleType")
        protected String href;
        @XmlAttribute(name = "vocab")
        @XmlSchemaType(name = "anySimpleType")
        protected String vocab;

        /**
         * Gets the value of the about property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAbout() {
            return about;
        }

        /**
         * Sets the value of the about property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAbout(String value) {
            this.about = value;
        }

        /**
         * Gets the value of the rel property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRel() {
            return rel;
        }

        /**
         * Sets the value of the rel property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRel(String value) {
            this.rel = value;
        }

        /**
         * Gets the value of the href property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the vocab property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVocab() {
            return vocab;
        }

        /**
         * Sets the value of the vocab property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVocab(String value) {
            this.vocab = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="podnositelj_zalbe" type="{http://localhost:8080/tipovi}Tosoba"/&gt;
     *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnositeljZalbe",
        "razlog"
    })
    public static class RazlogZalbe {

        @XmlElement(name = "podnositelj_zalbe", required = true)
        protected Tosoba podnositeljZalbe;
        @XmlElement(required = true)
        protected String razlog;
        @XmlAttribute(name = "about")
        @XmlSchemaType(name = "anySimpleType")
        protected String about;
        @XmlAttribute(name = "rel")
        @XmlSchemaType(name = "anySimpleType")
        protected String rel;
        @XmlAttribute(name = "href")
        @XmlSchemaType(name = "anySimpleType")
        protected String href;
        @XmlAttribute(name = "vocab")
        @XmlSchemaType(name = "anySimpleType")
        protected String vocab;

        /**
         * Gets the value of the podnositeljZalbe property.
         *
         * @return
         *     possible object is
         *     {@link Tosoba }
         *
         */
        public Tosoba getPodnositeljZalbe() {
            return podnositeljZalbe;
        }

        /**
         * Sets the value of the podnositeljZalbe property.
         *
         * @param value
         *     allowed object is
         *     {@link Tosoba }
         *
         */
        public void setPodnositeljZalbe(Tosoba value) {
            this.podnositeljZalbe = value;
        }

        /**
         * Gets the value of the razlog property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRazlog() {
            return razlog;
        }

        /**
         * Sets the value of the razlog property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRazlog(String value) {
            this.razlog = value;
        }

        /**
         * Gets the value of the about property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAbout() {
            return about;
        }

        /**
         * Sets the value of the about property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAbout(String value) {
            this.about = value;
        }

        /**
         * Gets the value of the rel property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRel() {
            return rel;
        }

        /**
         * Sets the value of the rel property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRel(String value) {
            this.rel = value;
        }

        /**
         * Gets the value of the href property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the vocab property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVocab() {
            return vocab;
        }

        /**
         * Sets the value of the vocab property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVocab(String value) {
            this.vocab = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="odgovor_na_zalbu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="obrazlozenje"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="uvod_obrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="postupajuci_po_zalbi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="dodatan_uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="odgovor_poverenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="upravni_spor"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="mesto"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="rok_prijema" type="{http://localhost:8080/tipovi}Trok"/&gt;
     *                   &lt;element name="taksa" type="{http://localhost:8080/tipovi}Ttrosak"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "odgovorNaZalbu",
        "obrazlozenje",
        "upravniSpor"
    })
    public static class TeloResenja {

        @XmlElement(name = "odgovor_na_zalbu", required = true)
        protected String odgovorNaZalbu;
        @XmlElement(required = true)
        protected Obrazlozenje obrazlozenje;
        @XmlElement(name = "upravni_spor", required = true)
        protected UpravniSpor upravniSpor;

        /**
         * Gets the value of the odgovorNaZalbu property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOdgovorNaZalbu() {
            return odgovorNaZalbu;
        }

        /**
         * Sets the value of the odgovorNaZalbu property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOdgovorNaZalbu(String value) {
            this.odgovorNaZalbu = value;
        }

        /**
         * Gets the value of the obrazlozenje property.
         *
         * @return
         *     possible object is
         *     {@link Obrazlozenje }
         *
         */
        public Obrazlozenje getObrazlozenje() {
            return obrazlozenje;
        }

        /**
         * Sets the value of the obrazlozenje property.
         *
         * @param value
         *     allowed object is
         *     {@link Obrazlozenje }
         *
         */
        public void setObrazlozenje(Obrazlozenje value) {
            this.obrazlozenje = value;
        }

        /**
         * Gets the value of the upravniSpor property.
         *
         * @return
         *     possible object is
         *     {@link UpravniSpor }
         *
         */
        public UpravniSpor getUpravniSpor() {
            return upravniSpor;
        }

        /**
         * Sets the value of the upravniSpor property.
         *
         * @param value
         *     allowed object is
         *     {@link UpravniSpor }
         *
         */
        public void setUpravniSpor(UpravniSpor value) {
            this.upravniSpor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="uvod_obrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="postupajuci_po_zalbi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="dodatan_uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="odgovor_poverenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "uvodObrazlozenja",
            "postupajuciPoZalbi",
            "uvid",
            "dodatanUvid",
            "odgovorPoverenika"
        })
        public static class Obrazlozenje {

            @XmlElement(name = "uvod_obrazlozenja", required = true)
            protected String uvodObrazlozenja;
            @XmlElement(name = "postupajuci_po_zalbi", required = true)
            protected String postupajuciPoZalbi;
            @XmlElement(required = true)
            protected String uvid;
            @XmlElement(name = "dodatan_uvid", required = true)
            protected String dodatanUvid;
            @XmlElement(name = "odgovor_poverenika", required = true)
            protected String odgovorPoverenika;

            /**
             * Gets the value of the uvodObrazlozenja property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUvodObrazlozenja() {
                return uvodObrazlozenja;
            }

            /**
             * Sets the value of the uvodObrazlozenja property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUvodObrazlozenja(String value) {
                this.uvodObrazlozenja = value;
            }

            /**
             * Gets the value of the postupajuciPoZalbi property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getPostupajuciPoZalbi() {
                return postupajuciPoZalbi;
            }

            /**
             * Sets the value of the postupajuciPoZalbi property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setPostupajuciPoZalbi(String value) {
                this.postupajuciPoZalbi = value;
            }

            /**
             * Gets the value of the uvid property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUvid() {
                return uvid;
            }

            /**
             * Sets the value of the uvid property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUvid(String value) {
                this.uvid = value;
            }

            /**
             * Gets the value of the dodatanUvid property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDodatanUvid() {
                return dodatanUvid;
            }

            /**
             * Sets the value of the dodatanUvid property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDodatanUvid(String value) {
                this.dodatanUvid = value;
            }

            /**
             * Gets the value of the odgovorPoverenika property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getOdgovorPoverenika() {
                return odgovorPoverenika;
            }

            /**
             * Sets the value of the odgovorPoverenika property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setOdgovorPoverenika(String value) {
                this.odgovorPoverenika = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="mesto"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="rok_prijema" type="{http://localhost:8080/tipovi}Trok"/&gt;
         *         &lt;element name="taksa" type="{http://localhost:8080/tipovi}Ttrosak"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mesto",
            "rokPrijema",
            "taksa"
        })
        public static class UpravniSpor {

            @XmlElement(required = true)
            protected Mesto mesto;
            @XmlElement(name = "rok_prijema", required = true)
            protected String rokPrijema;
            @XmlElement(required = true, type = String.class)
            @XmlJavaTypeAdapter(Adapter1.class)
            protected Double taksa;

            /**
             * Gets the value of the mesto property.
             *
             * @return
             *     possible object is
             *     {@link Mesto }
             *
             */
            public Mesto getMesto() {
                return mesto;
            }

            /**
             * Sets the value of the mesto property.
             *
             * @param value
             *     allowed object is
             *     {@link Mesto }
             *
             */
            public void setMesto(Mesto value) {
                this.mesto = value;
            }

            /**
             * Gets the value of the rokPrijema property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRokPrijema() {
                return rokPrijema;
            }

            /**
             * Sets the value of the rokPrijema property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRokPrijema(String value) {
                this.rokPrijema = value;
            }

            /**
             * Gets the value of the taksa property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public Double getTaksa() {
                return taksa;
            }

            /**
             * Sets the value of the taksa property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTaksa(Double value) {
                this.taksa = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Mesto {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "property")
                @XmlSchemaType(name = "anySimpleType")
                protected String property;
                @XmlAttribute(name = "datatype")
                @XmlSchemaType(name = "anySimpleType")
                protected String datatype;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the property property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getProperty() {
                    return property;
                }

                /**
                 * Sets the value of the property property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setProperty(String value) {
                    this.property = value;
                }

                /**
                 * Gets the value of the datatype property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDatatype() {
                    return datatype;
                }

                /**
                 * Sets the value of the datatype property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDatatype(String value) {
                    this.datatype = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="rezultat_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="informacije_predmeta"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="broj_predmeta"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;pattern value="(\d{3}-\d{2}-\d{4})?"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="datum_predmeta"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://localhost:8080/tipovi&gt;TdatumBroj"&gt;
     *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="datum_resenja"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
     *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rezultatResenja",
        "informacijePredmeta",
        "datumResenja"
    })
    public static class Zaglavlje {

        @XmlElement(name = "rezultat_resenja", required = true)
        protected String rezultatResenja;
        @XmlElement(name = "informacije_predmeta", required = true)
        protected InformacijePredmeta informacijePredmeta;
        @XmlElement(name = "datum_resenja", required = true)
        protected DatumResenja datumResenja;

        /**
         * Gets the value of the rezultatResenja property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRezultatResenja() {
            return rezultatResenja;
        }

        /**
         * Sets the value of the rezultatResenja property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRezultatResenja(String value) {
            this.rezultatResenja = value;
        }

        /**
         * Gets the value of the informacijePredmeta property.
         *
         * @return
         *     possible object is
         *     {@link InformacijePredmeta }
         *
         */
        public InformacijePredmeta getInformacijePredmeta() {
            return informacijePredmeta;
        }

        /**
         * Sets the value of the informacijePredmeta property.
         *
         * @param value
         *     allowed object is
         *     {@link InformacijePredmeta }
         *
         */
        public void setInformacijePredmeta(InformacijePredmeta value) {
            this.informacijePredmeta = value;
        }

        /**
         * Gets the value of the datumResenja property.
         *
         * @return
         *     possible object is
         *     {@link DatumResenja }
         *
         */
        public DatumResenja getDatumResenja() {
            return datumResenja;
        }

        /**
         * Sets the value of the datumResenja property.
         *
         * @param value
         *     allowed object is
         *     {@link DatumResenja }
         *
         */
        public void setDatumResenja(DatumResenja value) {
            this.datumResenja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
         *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DatumResenja {

            @XmlValue
            @XmlJavaTypeAdapter(DateAdapter.class)
            protected Date value;
            @XmlAttribute(name = "property")
            @XmlSchemaType(name = "anySimpleType")
            protected String property;
            @XmlAttribute(name = "datatype")
            @XmlSchemaType(name = "anySimpleType")
            protected String datatype;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public Date getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(Date value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                return property;
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="broj_predmeta"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;pattern value="(\d{3}-\d{2}-\d{4})?"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="datum_predmeta"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://localhost:8080/tipovi&gt;TdatumBroj"&gt;
         *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojPredmeta",
            "datumPredmeta"
        })
        public static class InformacijePredmeta {

            @XmlElement(name = "broj_predmeta", required = true)
            protected String brojPredmeta;
            @XmlElement(name = "datum_predmeta", required = true)
            protected DatumPredmeta datumPredmeta;

            /**
             * Gets the value of the brojPredmeta property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getBrojPredmeta() {
                return brojPredmeta;
            }

            /**
             * Sets the value of the brojPredmeta property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setBrojPredmeta(String value) {
                this.brojPredmeta = value;
            }

            /**
             * Gets the value of the datumPredmeta property.
             *
             * @return
             *     possible object is
             *     {@link DatumPredmeta }
             *
             */
            public DatumPredmeta getDatumPredmeta() {
                return datumPredmeta;
            }

            /**
             * Sets the value of the datumPredmeta property.
             *
             * @param value
             *     allowed object is
             *     {@link DatumPredmeta }
             *
             */
            public void setDatumPredmeta(DatumPredmeta value) {
                this.datumPredmeta = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://localhost:8080/tipovi&gt;TdatumBroj"&gt;
             *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class DatumPredmeta {

                @XmlValue
                @XmlJavaTypeAdapter(YearMonthAdapter.class)
                protected Date value;
                @XmlAttribute(name = "property")
                @XmlSchemaType(name = "anySimpleType")
                protected String property;
                @XmlAttribute(name = "datatype")
                @XmlSchemaType(name = "anySimpleType")
                protected String datatype;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public Date getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(Date value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the property property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProperty() {
                    return property;
                }

                /**
                 * Sets the value of the property property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProperty(String value) {
                    this.property = value;
                }

                /**
                 * Gets the value of the datatype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatatype() {
                    return datatype;
                }

                /**
                 * Sets the value of the datatype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatatype(String value) {
                    this.datatype = value;
                }

            }

        }

    }

}
