//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 12:18:48 AM CET 
//


package com.administration.services.model;

import com.administration.services.configs.DateAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="organ"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="sediste"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="listaZahteva"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="svrha_zahteva"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="1"/&gt;
 *                         &lt;maxInclusive value="4"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="nacin_dostave" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="detalji_predaje"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="mesto"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="datum"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
 *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="informacije_o_traziocu"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="drugi_kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipZahtev", propOrder = {
    "status",
    "organ",
    "listaZahteva",
    "detaljiPredaje",
    "informacijeOTraziocu"
})
@XmlRootElement(name = "zahtev", namespace = "http://localhost:8080/zahtevcir")
public class Zahtev {

    @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
    protected Status status;
    @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
    protected Organ organ;
    @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
    protected ListaZahteva listaZahteva;
    @XmlElement(name = "detalji_predaje", namespace = "http://localhost:8080/zahtevcir", required = true)
    protected DetaljiPredaje detaljiPredaje;
    @XmlElement(name = "informacije_o_traziocu", namespace = "http://localhost:8080/zahtevcir", required = true)
    protected InformacijeOTraziocu informacijeOTraziocu;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "rel")
    @XmlSchemaType(name = "anySimpleType")
    protected String rel;
    @XmlAttribute(name = "href")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;
    @XmlAttribute(name = "vocab")
    @XmlSchemaType(name = "anySimpleType")
    protected String vocab;

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link Status }
     *
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link Status }
     *
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the organ property.
     *
     * @return
     *     possible object is
     *     {@link Organ }
     *
     */
    public Organ getOrgan() {
        return organ;
    }

    /**
     * Sets the value of the organ property.
     *
     * @param value
     *     allowed object is
     *     {@link Organ }
     *
     */
    public void setOrgan(Organ value) {
        this.organ = value;
    }

    /**
     * Gets the value of the listaZahteva property.
     *
     * @return
     *     possible object is
     *     {@link ListaZahteva }
     *
     */
    public ListaZahteva getListaZahteva() {
        return listaZahteva;
    }

    /**
     * Sets the value of the listaZahteva property.
     *
     * @param value
     *     allowed object is
     *     {@link ListaZahteva }
     *
     */
    public void setListaZahteva(ListaZahteva value) {
        this.listaZahteva = value;
    }

    /**
     * Gets the value of the detaljiPredaje property.
     *
     * @return
     *     possible object is
     *     {@link DetaljiPredaje }
     *
     */
    public DetaljiPredaje getDetaljiPredaje() {
        return detaljiPredaje;
    }

    /**
     * Sets the value of the detaljiPredaje property.
     *
     * @param value
     *     allowed object is
     *     {@link DetaljiPredaje }
     *
     */
    public void setDetaljiPredaje(DetaljiPredaje value) {
        this.detaljiPredaje = value;
    }

    /**
     * Gets the value of the informacijeOTraziocu property.
     *
     * @return
     *     possible object is
     *     {@link InformacijeOTraziocu }
     *
     */
    public InformacijeOTraziocu getInformacijeOTraziocu() {
        return informacijeOTraziocu;
    }

    /**
     * Sets the value of the informacijeOTraziocu property.
     *
     * @param value
     *     allowed object is
     *     {@link InformacijeOTraziocu }
     *
     */
    public void setInformacijeOTraziocu(InformacijeOTraziocu value) {
        this.informacijeOTraziocu = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the rel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRel(String value) {
        this.rel = value;
    }

    /**
     * Gets the value of the href property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the vocab property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVocab(String value) {
        this.vocab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="mesto"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="datum"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
     *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mesto",
        "datum"
    })
    public static class DetaljiPredaje {

        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected Mesto mesto;
        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected Datum datum;

        /**
         * Gets the value of the mesto property.
         *
         * @return
         *     possible object is
         *     {@link Mesto }
         *
         */
        public Mesto getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         *
         * @param value
         *     allowed object is
         *     {@link Mesto }
         *
         */
        public void setMesto(Mesto value) {
            this.mesto = value;
        }

        /**
         * Gets the value of the datum property.
         *
         * @return
         *     possible object is
         *     {@link Datum }
         *
         */
        public Datum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         *
         * @param value
         *     allowed object is
         *     {@link Datum }
         *
         */
        public void setDatum(Datum value) {
            this.datum = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
         *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Datum {

            @XmlValue
            @XmlJavaTypeAdapter(DateAdapter.class)
            protected Date value;
            @XmlAttribute(name = "property")
            @XmlSchemaType(name = "anySimpleType")
            protected String property;
            @XmlAttribute(name = "datatype")
            @XmlSchemaType(name = "anySimpleType")
            protected String datatype;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public Date getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(Date value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                return property;
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Mesto {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            @XmlSchemaType(name = "anySimpleType")
            protected String property;
            @XmlAttribute(name = "datatype")
            @XmlSchemaType(name = "anySimpleType")
            protected String datatype;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                return property;
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="drugi_kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "adresa",
        "drugiKontakt"
    })
    public static class InformacijeOTraziocu {

        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String ime;
        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String prezime;
        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String adresa;
        @XmlElement(name = "drugi_kontakt", namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String drugiKontakt;
        @XmlAttribute(name = "about")
        @XmlSchemaType(name = "anySimpleType")
        protected String about;
        @XmlAttribute(name = "rel")
        @XmlSchemaType(name = "anySimpleType")
        protected String rel;
        @XmlAttribute(name = "href")
        @XmlSchemaType(name = "anySimpleType")
        protected String href;
        @XmlAttribute(name = "vocab")
        @XmlSchemaType(name = "anySimpleType")
        protected String vocab;

        /**
         * Gets the value of the ime property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the adresa property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAdresa(String value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the drugiKontakt property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDrugiKontakt() {
            return drugiKontakt;
        }

        /**
         * Sets the value of the drugiKontakt property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDrugiKontakt(String value) {
            this.drugiKontakt = value;
        }

        /**
         * Gets the value of the about property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAbout() {
            return about;
        }

        /**
         * Sets the value of the about property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAbout(String value) {
            this.about = value;
        }

        /**
         * Gets the value of the rel property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRel() {
            return rel;
        }

        /**
         * Sets the value of the rel property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRel(String value) {
            this.rel = value;
        }

        /**
         * Gets the value of the href property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the vocab property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVocab() {
            return vocab;
        }

        /**
         * Sets the value of the vocab property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVocab(String value) {
            this.vocab = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="svrha_zahteva"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="1"/&gt;
     *               &lt;maxInclusive value="4"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="nacin_dostave" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "svrhaZahteva",
        "nacinDostave",
        "opisInformacije"
    })
    public static class ListaZahteva {

        @XmlElement(name = "svrha_zahteva", namespace = "http://localhost:8080/zahtevcir")
        protected int svrhaZahteva;
        @XmlElement(name = "nacin_dostave", namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String nacinDostave;
        @XmlElement(name = "opis_informacije", namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String opisInformacije;

        /**
         * Gets the value of the svrhaZahteva property.
         *
         */
        public int getSvrhaZahteva() {
            return svrhaZahteva;
        }

        /**
         * Sets the value of the svrhaZahteva property.
         *
         */
        public void setSvrhaZahteva(int value) {
            this.svrhaZahteva = value;
        }

        /**
         * Gets the value of the nacinDostave property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNacinDostave() {
            return nacinDostave;
        }

        /**
         * Sets the value of the nacinDostave property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNacinDostave(String value) {
            this.nacinDostave = value;
        }

        /**
         * Gets the value of the opisInformacije property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOpisInformacije() {
            return opisInformacije;
        }

        /**
         * Sets the value of the opisInformacije property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOpisInformacije(String value) {
            this.opisInformacije = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="sediste"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "sediste"
    })
    public static class Organ {

        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected String naziv;
        @XmlElement(namespace = "http://localhost:8080/zahtevcir", required = true)
        protected Sediste sediste;

        /**
         * Gets the value of the naziv property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the sediste property.
         *
         * @return
         *     possible object is
         *     {@link Sediste }
         *
         */
        public Sediste getSediste() {
            return sediste;
        }

        /**
         * Sets the value of the sediste property.
         *
         * @param value
         *     allowed object is
         *     {@link Sediste }
         *
         */
        public void setSediste(Sediste value) {
            this.sediste = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Sediste {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            @XmlSchemaType(name = "anySimpleType")
            protected String property;
            @XmlAttribute(name = "datatype")
            @XmlSchemaType(name = "anySimpleType")
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                return property;
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Status {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

}
