//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 08:01:20 PM CET 
//


package resenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.resenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resenje }
     * 
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja }
     * 
     */
    public Resenje.TeloResenja createResenjeTeloResenja() {
        return new Resenje.TeloResenja();
    }

    /**
     * Create an instance of {@link Resenje.Zaglavlje }
     * 
     */
    public Resenje.Zaglavlje createResenjeZaglavlje() {
        return new Resenje.Zaglavlje();
    }

    /**
     * Create an instance of {@link Resenje.RazlogZalbe }
     * 
     */
    public Resenje.RazlogZalbe createResenjeRazlogZalbe() {
        return new Resenje.RazlogZalbe();
    }

    /**
     * Create an instance of {@link Tosoba }
     * 
     */
    public Tosoba createTosoba() {
        return new Tosoba();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja.Obrazlozenje }
     * 
     */
    public Resenje.TeloResenja.Obrazlozenje createResenjeTeloResenjaObrazlozenje() {
        return new Resenje.TeloResenja.Obrazlozenje();
    }

    /**
     * Create an instance of {@link Resenje.TeloResenja.UpravniSpor }
     * 
     */
    public Resenje.TeloResenja.UpravniSpor createResenjeTeloResenjaUpravniSpor() {
        return new Resenje.TeloResenja.UpravniSpor();
    }

    /**
     * Create an instance of {@link Resenje.Zaglavlje.InformacijePredmeta }
     * 
     */
    public Resenje.Zaglavlje.InformacijePredmeta createResenjeZaglavljeInformacijePredmeta() {
        return new Resenje.Zaglavlje.InformacijePredmeta();
    }

}
