//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 01:39:46 PM CET 
//


package resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zaglavlje"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="rezultat_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="informacije_predmeta"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="broj_predmeta"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;pattern value="(\d{3}-\d{2}-\d{4})?"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="datum_predmeta" type="{http://localhost:8080/resenje}TdatumBroj"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="datum_resenja" type="{http://localhost:8080/resenje}Tdatum"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="razlog_zalbe"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="podnositelj_zalbe" type="{http://localhost:8080/resenje}Tosoba"/&gt;
 *                   &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="telo_resenja"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="odgovor_na_zalbu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="obrazlozenje"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="uvod_obrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="postupajuci_po_zalbi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="dodatan_uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="odgovor_poverenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="upravni_spor"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="rok_prijema" type="{http://localhost:8080/resenje}Trok"/&gt;
 *                             &lt;element name="taksa" type="{http://localhost:8080/resenje}Ttrosak"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="poverenik" type="{http://localhost:8080/resenje}Tosoba"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zaglavlje",
    "razlogZalbe",
    "teloResenja",
    "poverenik"
})
@XmlRootElement(name = "resenje")
public class Resenje {

    @XmlElement(required = true)
    protected Resenje.Zaglavlje zaglavlje;
    @XmlElement(name = "razlog_zalbe", required = true)
    protected Resenje.RazlogZalbe razlogZalbe;
    @XmlElement(name = "telo_resenja", required = true)
    protected Resenje.TeloResenja teloResenja;
    @XmlElement(required = true)
    protected Tosoba poverenik;

    /**
     * Gets the value of the zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link Resenje.Zaglavlje }
     *     
     */
    public Resenje.Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resenje.Zaglavlje }
     *     
     */
    public void setZaglavlje(Resenje.Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the razlogZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Resenje.RazlogZalbe }
     *     
     */
    public Resenje.RazlogZalbe getRazlogZalbe() {
        return razlogZalbe;
    }

    /**
     * Sets the value of the razlogZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resenje.RazlogZalbe }
     *     
     */
    public void setRazlogZalbe(Resenje.RazlogZalbe value) {
        this.razlogZalbe = value;
    }

    /**
     * Gets the value of the teloResenja property.
     * 
     * @return
     *     possible object is
     *     {@link Resenje.TeloResenja }
     *     
     */
    public Resenje.TeloResenja getTeloResenja() {
        return teloResenja;
    }

    /**
     * Sets the value of the teloResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resenje.TeloResenja }
     *     
     */
    public void setTeloResenja(Resenje.TeloResenja value) {
        this.teloResenja = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link Tosoba }
     *     
     */
    public Tosoba getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tosoba }
     *     
     */
    public void setPoverenik(Tosoba value) {
        this.poverenik = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="podnositelj_zalbe" type="{http://localhost:8080/resenje}Tosoba"/&gt;
     *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnositeljZalbe",
        "razlog"
    })
    public static class RazlogZalbe {

        @XmlElement(name = "podnositelj_zalbe", required = true)
        protected Tosoba podnositeljZalbe;
        @XmlElement(required = true)
        protected String razlog;

        /**
         * Gets the value of the podnositeljZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link Tosoba }
         *     
         */
        public Tosoba getPodnositeljZalbe() {
            return podnositeljZalbe;
        }

        /**
         * Sets the value of the podnositeljZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tosoba }
         *     
         */
        public void setPodnositeljZalbe(Tosoba value) {
            this.podnositeljZalbe = value;
        }

        /**
         * Gets the value of the razlog property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazlog() {
            return razlog;
        }

        /**
         * Sets the value of the razlog property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazlog(String value) {
            this.razlog = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="odgovor_na_zalbu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="obrazlozenje"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="uvod_obrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="postupajuci_po_zalbi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="dodatan_uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="odgovor_poverenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="upravni_spor"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="rok_prijema" type="{http://localhost:8080/resenje}Trok"/&gt;
     *                   &lt;element name="taksa" type="{http://localhost:8080/resenje}Ttrosak"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "odgovorNaZalbu",
        "obrazlozenje",
        "upravniSpor"
    })
    public static class TeloResenja {

        @XmlElement(name = "odgovor_na_zalbu", required = true)
        protected String odgovorNaZalbu;
        @XmlElement(required = true)
        protected Resenje.TeloResenja.Obrazlozenje obrazlozenje;
        @XmlElement(name = "upravni_spor", required = true)
        protected Resenje.TeloResenja.UpravniSpor upravniSpor;

        /**
         * Gets the value of the odgovorNaZalbu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdgovorNaZalbu() {
            return odgovorNaZalbu;
        }

        /**
         * Sets the value of the odgovorNaZalbu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdgovorNaZalbu(String value) {
            this.odgovorNaZalbu = value;
        }

        /**
         * Gets the value of the obrazlozenje property.
         * 
         * @return
         *     possible object is
         *     {@link Resenje.TeloResenja.Obrazlozenje }
         *     
         */
        public Resenje.TeloResenja.Obrazlozenje getObrazlozenje() {
            return obrazlozenje;
        }

        /**
         * Sets the value of the obrazlozenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link Resenje.TeloResenja.Obrazlozenje }
         *     
         */
        public void setObrazlozenje(Resenje.TeloResenja.Obrazlozenje value) {
            this.obrazlozenje = value;
        }

        /**
         * Gets the value of the upravniSpor property.
         * 
         * @return
         *     possible object is
         *     {@link Resenje.TeloResenja.UpravniSpor }
         *     
         */
        public Resenje.TeloResenja.UpravniSpor getUpravniSpor() {
            return upravniSpor;
        }

        /**
         * Sets the value of the upravniSpor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Resenje.TeloResenja.UpravniSpor }
         *     
         */
        public void setUpravniSpor(Resenje.TeloResenja.UpravniSpor value) {
            this.upravniSpor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="uvod_obrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="postupajuci_po_zalbi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="dodatan_uvid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="odgovor_poverenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "uvodObrazlozenja",
            "postupajuciPoZalbi",
            "uvid",
            "dodatanUvid",
            "odgovorPoverenika"
        })
        public static class Obrazlozenje {

            @XmlElement(name = "uvod_obrazlozenja", required = true)
            protected String uvodObrazlozenja;
            @XmlElement(name = "postupajuci_po_zalbi", required = true)
            protected String postupajuciPoZalbi;
            @XmlElement(required = true)
            protected String uvid;
            @XmlElement(name = "dodatan_uvid", required = true)
            protected String dodatanUvid;
            @XmlElement(name = "odgovor_poverenika", required = true)
            protected String odgovorPoverenika;

            /**
             * Gets the value of the uvodObrazlozenja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUvodObrazlozenja() {
                return uvodObrazlozenja;
            }

            /**
             * Sets the value of the uvodObrazlozenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUvodObrazlozenja(String value) {
                this.uvodObrazlozenja = value;
            }

            /**
             * Gets the value of the postupajuciPoZalbi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostupajuciPoZalbi() {
                return postupajuciPoZalbi;
            }

            /**
             * Sets the value of the postupajuciPoZalbi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostupajuciPoZalbi(String value) {
                this.postupajuciPoZalbi = value;
            }

            /**
             * Gets the value of the uvid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUvid() {
                return uvid;
            }

            /**
             * Sets the value of the uvid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUvid(String value) {
                this.uvid = value;
            }

            /**
             * Gets the value of the dodatanUvid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDodatanUvid() {
                return dodatanUvid;
            }

            /**
             * Sets the value of the dodatanUvid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDodatanUvid(String value) {
                this.dodatanUvid = value;
            }

            /**
             * Gets the value of the odgovorPoverenika property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOdgovorPoverenika() {
                return odgovorPoverenika;
            }

            /**
             * Sets the value of the odgovorPoverenika property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOdgovorPoverenika(String value) {
                this.odgovorPoverenika = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="rok_prijema" type="{http://localhost:8080/resenje}Trok"/&gt;
         *         &lt;element name="taksa" type="{http://localhost:8080/resenje}Ttrosak"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mesto",
            "rokPrijema",
            "taksa"
        })
        public static class UpravniSpor {

            @XmlElement(required = true)
            protected String mesto;
            @XmlElement(name = "rok_prijema", required = true)
            protected String rokPrijema;
            @XmlElement(required = true)
            protected String taksa;

            /**
             * Gets the value of the mesto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMesto() {
                return mesto;
            }

            /**
             * Sets the value of the mesto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMesto(String value) {
                this.mesto = value;
            }

            /**
             * Gets the value of the rokPrijema property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRokPrijema() {
                return rokPrijema;
            }

            /**
             * Sets the value of the rokPrijema property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRokPrijema(String value) {
                this.rokPrijema = value;
            }

            /**
             * Gets the value of the taksa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaksa() {
                return taksa;
            }

            /**
             * Sets the value of the taksa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaksa(String value) {
                this.taksa = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="rezultat_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="informacije_predmeta"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="broj_predmeta"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;pattern value="(\d{3}-\d{2}-\d{4})?"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="datum_predmeta" type="{http://localhost:8080/resenje}TdatumBroj"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="datum_resenja" type="{http://localhost:8080/resenje}Tdatum"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rezultatResenja",
        "informacijePredmeta",
        "datumResenja"
    })
    public static class Zaglavlje {

        @XmlElement(name = "rezultat_resenja", required = true)
        protected String rezultatResenja;
        @XmlElement(name = "informacije_predmeta", required = true)
        protected Resenje.Zaglavlje.InformacijePredmeta informacijePredmeta;
        @XmlElement(name = "datum_resenja", required = true)
        protected String datumResenja;

        /**
         * Gets the value of the rezultatResenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRezultatResenja() {
            return rezultatResenja;
        }

        /**
         * Sets the value of the rezultatResenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRezultatResenja(String value) {
            this.rezultatResenja = value;
        }

        /**
         * Gets the value of the informacijePredmeta property.
         * 
         * @return
         *     possible object is
         *     {@link Resenje.Zaglavlje.InformacijePredmeta }
         *     
         */
        public Resenje.Zaglavlje.InformacijePredmeta getInformacijePredmeta() {
            return informacijePredmeta;
        }

        /**
         * Sets the value of the informacijePredmeta property.
         * 
         * @param value
         *     allowed object is
         *     {@link Resenje.Zaglavlje.InformacijePredmeta }
         *     
         */
        public void setInformacijePredmeta(Resenje.Zaglavlje.InformacijePredmeta value) {
            this.informacijePredmeta = value;
        }

        /**
         * Gets the value of the datumResenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatumResenja() {
            return datumResenja;
        }

        /**
         * Sets the value of the datumResenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumResenja(String value) {
            this.datumResenja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="broj_predmeta"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;pattern value="(\d{3}-\d{2}-\d{4})?"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="datum_predmeta" type="{http://localhost:8080/resenje}TdatumBroj"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojPredmeta",
            "datumPredmeta"
        })
        public static class InformacijePredmeta {

            @XmlElement(name = "broj_predmeta", required = true)
            protected String brojPredmeta;
            @XmlElement(name = "datum_predmeta", required = true)
            protected String datumPredmeta;

            /**
             * Gets the value of the brojPredmeta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrojPredmeta() {
                return brojPredmeta;
            }

            /**
             * Sets the value of the brojPredmeta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrojPredmeta(String value) {
                this.brojPredmeta = value;
            }

            /**
             * Gets the value of the datumPredmeta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatumPredmeta() {
                return datumPredmeta;
            }

            /**
             * Sets the value of the datumPredmeta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatumPredmeta(String value) {
                this.datumPredmeta = value;
            }

        }

    }

}
