//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:38:10 PM CET 
//


package obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zaglavlje"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="organ"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="broj_predmeta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="datum" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
 *                   &lt;element name="podnosioc_zahteva"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="telo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="trazena_informacija"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="datum_informacija" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
 *                             &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="uvid"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="vreme"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="datum" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
 *                                       &lt;element name="cas" type="{http://localhost:8080/obavestenje}cas"/&gt;
 *                                       &lt;element name="trajanje"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="pocetak" type="{http://localhost:8080/obavestenje}cas"/&gt;
 *                                                 &lt;element name="kraj" type="{http://localhost:8080/obavestenje}cas"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="adresa"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="trosak" type="{http://localhost:8080/obavestenje}Ttrosak"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zaglavlje",
    "telo"
})
@XmlRootElement(name = "obavestenje")
public class Obavestenje {

    @XmlElement(required = true)
    protected Obavestenje.Zaglavlje zaglavlje;
    @XmlElement(required = true)
    protected Obavestenje.Telo telo;

    /**
     * Gets the value of the zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.Zaglavlje }
     *     
     */
    public Obavestenje.Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.Zaglavlje }
     *     
     */
    public void setZaglavlje(Obavestenje.Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the telo property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.Telo }
     *     
     */
    public Obavestenje.Telo getTelo() {
        return telo;
    }

    /**
     * Sets the value of the telo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.Telo }
     *     
     */
    public void setTelo(Obavestenje.Telo value) {
        this.telo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="trazena_informacija"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="datum_informacija" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
     *                   &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="uvid"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="vreme"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="datum" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
     *                             &lt;element name="cas" type="{http://localhost:8080/obavestenje}cas"/&gt;
     *                             &lt;element name="trajanje"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="pocetak" type="{http://localhost:8080/obavestenje}cas"/&gt;
     *                                       &lt;element name="kraj" type="{http://localhost:8080/obavestenje}cas"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="adresa"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="trosak" type="{http://localhost:8080/obavestenje}Ttrosak"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trazenaInformacija",
        "uvid",
        "trosak"
    })
    public static class Telo {

        @XmlElement(name = "trazena_informacija", required = true)
        protected Obavestenje.Telo.TrazenaInformacija trazenaInformacija;
        @XmlElement(required = true)
        protected Obavestenje.Telo.Uvid uvid;
        @XmlElement(required = true, nillable = true)
        protected String trosak;

        /**
         * Gets the value of the trazenaInformacija property.
         * 
         * @return
         *     possible object is
         *     {@link Obavestenje.Telo.TrazenaInformacija }
         *     
         */
        public Obavestenje.Telo.TrazenaInformacija getTrazenaInformacija() {
            return trazenaInformacija;
        }

        /**
         * Sets the value of the trazenaInformacija property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obavestenje.Telo.TrazenaInformacija }
         *     
         */
        public void setTrazenaInformacija(Obavestenje.Telo.TrazenaInformacija value) {
            this.trazenaInformacija = value;
        }

        /**
         * Gets the value of the uvid property.
         * 
         * @return
         *     possible object is
         *     {@link Obavestenje.Telo.Uvid }
         *     
         */
        public Obavestenje.Telo.Uvid getUvid() {
            return uvid;
        }

        /**
         * Sets the value of the uvid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obavestenje.Telo.Uvid }
         *     
         */
        public void setUvid(Obavestenje.Telo.Uvid value) {
            this.uvid = value;
        }

        /**
         * Gets the value of the trosak property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrosak() {
            return trosak;
        }

        /**
         * Sets the value of the trosak property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrosak(String value) {
            this.trosak = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="datum_informacija" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
         *         &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datumInformacija",
            "opisInformacije"
        })
        public static class TrazenaInformacija {

            @XmlElement(name = "datum_informacija", required = true)
            protected String datumInformacija;
            @XmlElement(name = "opis_informacije", required = true)
            protected String opisInformacije;

            /**
             * Gets the value of the datumInformacija property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatumInformacija() {
                return datumInformacija;
            }

            /**
             * Sets the value of the datumInformacija property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatumInformacija(String value) {
                this.datumInformacija = value;
            }

            /**
             * Gets the value of the opisInformacije property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOpisInformacije() {
                return opisInformacije;
            }

            /**
             * Sets the value of the opisInformacije property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOpisInformacije(String value) {
                this.opisInformacije = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="vreme"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="datum" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
         *                   &lt;element name="cas" type="{http://localhost:8080/obavestenje}cas"/&gt;
         *                   &lt;element name="trajanje"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="pocetak" type="{http://localhost:8080/obavestenje}cas"/&gt;
         *                             &lt;element name="kraj" type="{http://localhost:8080/obavestenje}cas"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="adresa"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vreme",
            "adresa"
        })
        public static class Uvid {

            @XmlElement(required = true)
            protected Obavestenje.Telo.Uvid.Vreme vreme;
            @XmlElement(required = true)
            protected Obavestenje.Telo.Uvid.Adresa adresa;

            /**
             * Gets the value of the vreme property.
             * 
             * @return
             *     possible object is
             *     {@link Obavestenje.Telo.Uvid.Vreme }
             *     
             */
            public Obavestenje.Telo.Uvid.Vreme getVreme() {
                return vreme;
            }

            /**
             * Sets the value of the vreme property.
             * 
             * @param value
             *     allowed object is
             *     {@link Obavestenje.Telo.Uvid.Vreme }
             *     
             */
            public void setVreme(Obavestenje.Telo.Uvid.Vreme value) {
                this.vreme = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link Obavestenje.Telo.Uvid.Adresa }
             *     
             */
            public Obavestenje.Telo.Uvid.Adresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link Obavestenje.Telo.Uvid.Adresa }
             *     
             */
            public void setAdresa(Obavestenje.Telo.Uvid.Adresa value) {
                this.adresa = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mesto",
                "ulica",
                "broj",
                "brKancelarije"
            })
            public static class Adresa {

                @XmlElement(required = true)
                protected String mesto;
                @XmlElement(required = true)
                protected String ulica;
                @XmlElement(required = true)
                protected String broj;
                @XmlElement(name = "br_kancelarije", required = true)
                protected String brKancelarije;

                /**
                 * Gets the value of the mesto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMesto() {
                    return mesto;
                }

                /**
                 * Sets the value of the mesto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMesto(String value) {
                    this.mesto = value;
                }

                /**
                 * Gets the value of the ulica property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUlica() {
                    return ulica;
                }

                /**
                 * Sets the value of the ulica property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUlica(String value) {
                    this.ulica = value;
                }

                /**
                 * Gets the value of the broj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBroj() {
                    return broj;
                }

                /**
                 * Sets the value of the broj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBroj(String value) {
                    this.broj = value;
                }

                /**
                 * Gets the value of the brKancelarije property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBrKancelarije() {
                    return brKancelarije;
                }

                /**
                 * Sets the value of the brKancelarije property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBrKancelarije(String value) {
                    this.brKancelarije = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="datum" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
             *         &lt;element name="cas" type="{http://localhost:8080/obavestenje}cas"/&gt;
             *         &lt;element name="trajanje"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="pocetak" type="{http://localhost:8080/obavestenje}cas"/&gt;
             *                   &lt;element name="kraj" type="{http://localhost:8080/obavestenje}cas"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datum",
                "cas",
                "trajanje"
            })
            public static class Vreme {

                @XmlElement(required = true)
                protected String datum;
                @XmlElement(required = true)
                protected String cas;
                @XmlElement(required = true)
                protected Obavestenje.Telo.Uvid.Vreme.Trajanje trajanje;

                /**
                 * Gets the value of the datum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatum() {
                    return datum;
                }

                /**
                 * Sets the value of the datum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatum(String value) {
                    this.datum = value;
                }

                /**
                 * Gets the value of the cas property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCas() {
                    return cas;
                }

                /**
                 * Sets the value of the cas property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCas(String value) {
                    this.cas = value;
                }

                /**
                 * Gets the value of the trajanje property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Obavestenje.Telo.Uvid.Vreme.Trajanje }
                 *     
                 */
                public Obavestenje.Telo.Uvid.Vreme.Trajanje getTrajanje() {
                    return trajanje;
                }

                /**
                 * Sets the value of the trajanje property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Obavestenje.Telo.Uvid.Vreme.Trajanje }
                 *     
                 */
                public void setTrajanje(Obavestenje.Telo.Uvid.Vreme.Trajanje value) {
                    this.trajanje = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="pocetak" type="{http://localhost:8080/obavestenje}cas"/&gt;
                 *         &lt;element name="kraj" type="{http://localhost:8080/obavestenje}cas"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "pocetak",
                    "kraj"
                })
                public static class Trajanje {

                    @XmlElement(required = true)
                    protected String pocetak;
                    @XmlElement(required = true)
                    protected String kraj;

                    /**
                     * Gets the value of the pocetak property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPocetak() {
                        return pocetak;
                    }

                    /**
                     * Sets the value of the pocetak property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPocetak(String value) {
                        this.pocetak = value;
                    }

                    /**
                     * Gets the value of the kraj property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getKraj() {
                        return kraj;
                    }

                    /**
                     * Sets the value of the kraj property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setKraj(String value) {
                        this.kraj = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="organ"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="broj_predmeta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="datum" type="{http://localhost:8080/obavestenje}Tdatum"/&gt;
     *         &lt;element name="podnosioc_zahteva"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organ",
        "brojPredmeta",
        "datum",
        "podnosiocZahteva"
    })
    public static class Zaglavlje {

        @XmlElement(required = true)
        protected Obavestenje.Zaglavlje.Organ organ;
        @XmlElement(name = "broj_predmeta", required = true)
        protected String brojPredmeta;
        @XmlElement(required = true)
        protected String datum;
        @XmlElement(name = "podnosioc_zahteva", required = true)
        protected Obavestenje.Zaglavlje.PodnosiocZahteva podnosiocZahteva;

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link Obavestenje.Zaglavlje.Organ }
         *     
         */
        public Obavestenje.Zaglavlje.Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obavestenje.Zaglavlje.Organ }
         *     
         */
        public void setOrgan(Obavestenje.Zaglavlje.Organ value) {
            this.organ = value;
        }

        /**
         * Gets the value of the brojPredmeta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPredmeta() {
            return brojPredmeta;
        }

        /**
         * Sets the value of the brojPredmeta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPredmeta(String value) {
            this.brojPredmeta = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatum(String value) {
            this.datum = value;
        }

        /**
         * Gets the value of the podnosiocZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link Obavestenje.Zaglavlje.PodnosiocZahteva }
         *     
         */
        public Obavestenje.Zaglavlje.PodnosiocZahteva getPodnosiocZahteva() {
            return podnosiocZahteva;
        }

        /**
         * Sets the value of the podnosiocZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obavestenje.Zaglavlje.PodnosiocZahteva }
         *     
         */
        public void setPodnosiocZahteva(Obavestenje.Zaglavlje.PodnosiocZahteva value) {
            this.podnosiocZahteva = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivOrgana",
            "sedisteOrgana"
        })
        public static class Organ {

            @XmlElement(name = "naziv_organa", required = true)
            protected String nazivOrgana;
            @XmlElement(name = "sediste_organa", required = true)
            protected String sedisteOrgana;

            /**
             * Gets the value of the nazivOrgana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivOrgana() {
                return nazivOrgana;
            }

            /**
             * Sets the value of the nazivOrgana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivOrgana(String value) {
                this.nazivOrgana = value;
            }

            /**
             * Gets the value of the sedisteOrgana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSedisteOrgana() {
                return sedisteOrgana;
            }

            /**
             * Sets the value of the sedisteOrgana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSedisteOrgana(String value) {
                this.sedisteOrgana = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "naziv",
            "adresa"
        })
        public static class PodnosiocZahteva {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;
            @XmlElement(required = true)
            protected String naziv;
            @XmlElement(required = true)
            protected String adresa;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdresa(String value) {
                this.adresa = value;
            }

        }

    }

}
