//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:38:10 PM CET 
//


package obavestenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo }
     * 
     */
    public Obavestenje.Telo createObavestenjeTelo() {
        return new Obavestenje.Telo();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid }
     * 
     */
    public Obavestenje.Telo.Uvid createObavestenjeTeloUvid() {
        return new Obavestenje.Telo.Uvid();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid.Vreme }
     * 
     */
    public Obavestenje.Telo.Uvid.Vreme createObavestenjeTeloUvidVreme() {
        return new Obavestenje.Telo.Uvid.Vreme();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje }
     * 
     */
    public Obavestenje.Zaglavlje createObavestenjeZaglavlje() {
        return new Obavestenje.Zaglavlje();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.TrazenaInformacija }
     * 
     */
    public Obavestenje.Telo.TrazenaInformacija createObavestenjeTeloTrazenaInformacija() {
        return new Obavestenje.Telo.TrazenaInformacija();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid.Adresa }
     * 
     */
    public Obavestenje.Telo.Uvid.Adresa createObavestenjeTeloUvidAdresa() {
        return new Obavestenje.Telo.Uvid.Adresa();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.Uvid.Vreme.Trajanje }
     * 
     */
    public Obavestenje.Telo.Uvid.Vreme.Trajanje createObavestenjeTeloUvidVremeTrajanje() {
        return new Obavestenje.Telo.Uvid.Vreme.Trajanje();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje.Organ }
     * 
     */
    public Obavestenje.Zaglavlje.Organ createObavestenjeZaglavljeOrgan() {
        return new Obavestenje.Zaglavlje.Organ();
    }

    /**
     * Create an instance of {@link Obavestenje.Zaglavlje.PodnosiocZahteva }
     * 
     */
    public Obavestenje.Zaglavlje.PodnosiocZahteva createObavestenjeZaglavljePodnosiocZahteva() {
        return new Obavestenje.Zaglavlje.PodnosiocZahteva();
    }

}
