//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 12:18:48 AM CET 
//


package com.administration.services.model;

import com.administration.services.configs.DateAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zaglavlje"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="organ"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="sediste_organa"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="broj_predmeta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="datum"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
 *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="podnosioc_zahteva"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="telo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="trazena_informacija"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="datum_informacija"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
 *                                     &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="uvid"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="vreme"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="datum" type="{http://localhost:8080/tipovi}Tdatum"/&gt;
 *                                       &lt;element name="cas" type="{http://localhost:8080/tipovi}cas"/&gt;
 *                                       &lt;element name="trajanje"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="pocetak" type="{http://localhost:8080/tipovi}cas"/&gt;
 *                                                 &lt;element name="kraj" type="{http://localhost:8080/tipovi}cas"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="adresa"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="trosak" type="{http://localhost:8080/tipovi}Ttrosak"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipObavestenje", propOrder = {
    "zaglavlje",
    "telo"
})
@XmlRootElement(name = "obavestenje", namespace = "http://localhost:8080/obavestenje")
public class Obavestenje {

    @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
    protected Zaglavlje zaglavlje;
    @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
    protected Telo telo;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "rel")
    @XmlSchemaType(name = "anySimpleType")
    protected String rel;
    @XmlAttribute(name = "href")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;
    @XmlAttribute(name = "vocab")
    @XmlSchemaType(name = "anySimpleType")
    protected String vocab;

    /**
     * Gets the value of the zaglavlje property.
     *
     * @return
     *     possible object is
     *     {@link Zaglavlje }
     *
     */
    public Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     *
     * @param value
     *     allowed object is
     *     {@link Zaglavlje }
     *
     */
    public void setZaglavlje(Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the telo property.
     *
     * @return
     *     possible object is
     *     {@link Telo }
     *
     */
    public Telo getTelo() {
        return telo;
    }

    /**
     * Sets the value of the telo property.
     *
     * @param value
     *     allowed object is
     *     {@link Telo }
     *
     */
    public void setTelo(Telo value) {
        this.telo = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the rel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRel(String value) {
        this.rel = value;
    }

    /**
     * Gets the value of the href property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the vocab property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVocab(String value) {
        this.vocab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="trazena_informacija"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="datum_informacija"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
     *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="uvid"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="vreme"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="datum" type="{http://localhost:8080/tipovi}Tdatum"/&gt;
     *                             &lt;element name="cas" type="{http://localhost:8080/tipovi}cas"/&gt;
     *                             &lt;element name="trajanje"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="pocetak" type="{http://localhost:8080/tipovi}cas"/&gt;
     *                                       &lt;element name="kraj" type="{http://localhost:8080/tipovi}cas"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="adresa"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="trosak" type="{http://localhost:8080/tipovi}Ttrosak"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trazenaInformacija",
        "uvid",
        "trosak"
    })
    public static class Telo {

        @XmlElement(name = "trazena_informacija", namespace = "http://localhost:8080/obavestenje", required = true)
        protected TrazenaInformacija trazenaInformacija;
        @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
        protected Uvid uvid;
        @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true, type = String.class, nillable = true)
        @XmlJavaTypeAdapter(Adapter1 .class)
        protected Double trosak;

        /**
         * Gets the value of the trazenaInformacija property.
         *
         * @return
         *     possible object is
         *     {@link TrazenaInformacija }
         *
         */
        public TrazenaInformacija getTrazenaInformacija() {
            return trazenaInformacija;
        }

        /**
         * Sets the value of the trazenaInformacija property.
         *
         * @param value
         *     allowed object is
         *     {@link TrazenaInformacija }
         *
         */
        public void setTrazenaInformacija(TrazenaInformacija value) {
            this.trazenaInformacija = value;
        }

        /**
         * Gets the value of the uvid property.
         *
         * @return
         *     possible object is
         *     {@link Uvid }
         *
         */
        public Uvid getUvid() {
            return uvid;
        }

        /**
         * Sets the value of the uvid property.
         *
         * @param value
         *     allowed object is
         *     {@link Uvid }
         *
         */
        public void setUvid(Uvid value) {
            this.uvid = value;
        }

        /**
         * Gets the value of the trosak property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public Double getTrosak() {
            return trosak;
        }

        /**
         * Sets the value of the trosak property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setTrosak(Double value) {
            this.trosak = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="datum_informacija"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
         *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="opis_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributesResource"/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datumInformacija",
            "opisInformacije"
        })
        public static class TrazenaInformacija {

            @XmlElement(name = "datum_informacija", namespace = "http://localhost:8080/obavestenje", required = true)
            protected DatumInformacija datumInformacija;
            @XmlElement(name = "opis_informacije", namespace = "http://localhost:8080/obavestenje", required = true)
            protected String opisInformacije;
            @XmlAttribute(name = "about")
            @XmlSchemaType(name = "anySimpleType")
            protected String about;
            @XmlAttribute(name = "rel")
            @XmlSchemaType(name = "anySimpleType")
            protected String rel;
            @XmlAttribute(name = "href")
            @XmlSchemaType(name = "anySimpleType")
            protected String href;
            @XmlAttribute(name = "vocab")
            @XmlSchemaType(name = "anySimpleType")
            protected String vocab;

            /**
             * Gets the value of the datumInformacija property.
             *
             * @return
             *     possible object is
             *     {@link DatumInformacija }
             *
             */
            public DatumInformacija getDatumInformacija() {
                return datumInformacija;
            }

            /**
             * Sets the value of the datumInformacija property.
             *
             * @param value
             *     allowed object is
             *     {@link DatumInformacija }
             *
             */
            public void setDatumInformacija(DatumInformacija value) {
                this.datumInformacija = value;
            }

            /**
             * Gets the value of the opisInformacije property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getOpisInformacije() {
                return opisInformacije;
            }

            /**
             * Sets the value of the opisInformacije property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setOpisInformacije(String value) {
                this.opisInformacije = value;
            }

            /**
             * Gets the value of the about property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAbout() {
                return about;
            }

            /**
             * Sets the value of the about property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAbout(String value) {
                this.about = value;
            }

            /**
             * Gets the value of the rel property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRel() {
                return rel;
            }

            /**
             * Sets the value of the rel property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRel(String value) {
                this.rel = value;
            }

            /**
             * Gets the value of the href property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setHref(String value) {
                this.href = value;
            }

            /**
             * Gets the value of the vocab property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getVocab() {
                return vocab;
            }

            /**
             * Sets the value of the vocab property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setVocab(String value) {
                this.vocab = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
             *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class DatumInformacija {

                @XmlValue
                @XmlJavaTypeAdapter(DateAdapter.class)
                protected Date value;
                @XmlAttribute(name = "property")
                @XmlSchemaType(name = "anySimpleType")
                protected String property;
                @XmlAttribute(name = "datatype")
                @XmlSchemaType(name = "anySimpleType")
                protected String datatype;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public Date getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(Date value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the property property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getProperty() {
                    return property;
                }

                /**
                 * Sets the value of the property property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setProperty(String value) {
                    this.property = value;
                }

                /**
                 * Gets the value of the datatype property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDatatype() {
                    return datatype;
                }

                /**
                 * Sets the value of the datatype property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDatatype(String value) {
                    this.datatype = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="vreme"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="datum" type="{http://localhost:8080/tipovi}Tdatum"/&gt;
         *                   &lt;element name="cas" type="{http://localhost:8080/tipovi}cas"/&gt;
         *                   &lt;element name="trajanje"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="pocetak" type="{http://localhost:8080/tipovi}cas"/&gt;
         *                             &lt;element name="kraj" type="{http://localhost:8080/tipovi}cas"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="adresa"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vreme",
            "adresa"
        })
        public static class Uvid {

            @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
            protected Vreme vreme;
            @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
            protected Adresa adresa;

            /**
             * Gets the value of the vreme property.
             *
             * @return
             *     possible object is
             *     {@link Vreme }
             *
             */
            public Vreme getVreme() {
                return vreme;
            }

            /**
             * Sets the value of the vreme property.
             *
             * @param value
             *     allowed object is
             *     {@link Vreme }
             *
             */
            public void setVreme(Vreme value) {
                this.vreme = value;
            }

            /**
             * Gets the value of the adresa property.
             *
             * @return
             *     possible object is
             *     {@link Adresa }
             *
             */
            public Adresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             *
             * @param value
             *     allowed object is
             *     {@link Adresa }
             *
             */
            public void setAdresa(Adresa value) {
                this.adresa = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="br_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mesto",
                "ulica",
                "broj",
                "brKancelarije"
            })
            public static class Adresa {

                @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                protected String mesto;
                @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                protected String ulica;
                @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                protected String broj;
                @XmlElement(name = "br_kancelarije", namespace = "http://localhost:8080/obavestenje", required = true)
                protected String brKancelarije;

                /**
                 * Gets the value of the mesto property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getMesto() {
                    return mesto;
                }

                /**
                 * Sets the value of the mesto property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setMesto(String value) {
                    this.mesto = value;
                }

                /**
                 * Gets the value of the ulica property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getUlica() {
                    return ulica;
                }

                /**
                 * Sets the value of the ulica property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setUlica(String value) {
                    this.ulica = value;
                }

                /**
                 * Gets the value of the broj property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getBroj() {
                    return broj;
                }

                /**
                 * Sets the value of the broj property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setBroj(String value) {
                    this.broj = value;
                }

                /**
                 * Gets the value of the brKancelarije property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getBrKancelarije() {
                    return brKancelarije;
                }

                /**
                 * Sets the value of the brKancelarije property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setBrKancelarije(String value) {
                    this.brKancelarije = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="datum" type="{http://localhost:8080/tipovi}Tdatum"/&gt;
             *         &lt;element name="cas" type="{http://localhost:8080/tipovi}cas"/&gt;
             *         &lt;element name="trajanje"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="pocetak" type="{http://localhost:8080/tipovi}cas"/&gt;
             *                   &lt;element name="kraj" type="{http://localhost:8080/tipovi}cas"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datum",
                "cas",
                "trajanje"
            })
            public static class Vreme {

                @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true, type = String.class)
                @XmlJavaTypeAdapter(DateAdapter.class)
                protected Date datum;
                @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                protected String cas;
                @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                protected Trajanje trajanje;

                /**
                 * Gets the value of the datum property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public Date getDatum() {
                    return datum;
                }

                /**
                 * Sets the value of the datum property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDatum(Date value) {
                    this.datum = value;
                }

                /**
                 * Gets the value of the cas property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCas() {
                    return cas;
                }

                /**
                 * Sets the value of the cas property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCas(String value) {
                    this.cas = value;
                }

                /**
                 * Gets the value of the trajanje property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Trajanje }
                 *
                 */
                public Trajanje getTrajanje() {
                    return trajanje;
                }

                /**
                 * Sets the value of the trajanje property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Trajanje }
                 *
                 */
                public void setTrajanje(Trajanje value) {
                    this.trajanje = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="pocetak" type="{http://localhost:8080/tipovi}cas"/&gt;
                 *         &lt;element name="kraj" type="{http://localhost:8080/tipovi}cas"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "pocetak",
                    "kraj"
                })
                public static class Trajanje {

                    @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                    protected String pocetak;
                    @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
                    protected String kraj;

                    /**
                     * Gets the value of the pocetak property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getPocetak() {
                        return pocetak;
                    }

                    /**
                     * Sets the value of the pocetak property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setPocetak(String value) {
                        this.pocetak = value;
                    }

                    /**
                     * Gets the value of the kraj property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getKraj() {
                        return kraj;
                    }

                    /**
                     * Sets the value of the kraj property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setKraj(String value) {
                        this.kraj = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="organ"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="sediste_organa"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="broj_predmeta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="datum"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
     *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="podnosioc_zahteva"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organ",
        "brojPredmeta",
        "datum",
        "podnosiocZahteva"
    })
    public static class Zaglavlje {

        @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
        protected Organ organ;
        @XmlElement(name = "broj_predmeta", namespace = "http://localhost:8080/obavestenje", required = true)
        protected String brojPredmeta;
        @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
        protected Datum datum;
        @XmlElement(name = "podnosioc_zahteva", namespace = "http://localhost:8080/obavestenje", required = true)
        protected PodnosiocZahteva podnosiocZahteva;

        /**
         * Gets the value of the organ property.
         *
         * @return
         *     possible object is
         *     {@link Organ }
         *
         */
        public Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         *
         * @param value
         *     allowed object is
         *     {@link Organ }
         *
         */
        public void setOrgan(Organ value) {
            this.organ = value;
        }

        /**
         * Gets the value of the brojPredmeta property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getBrojPredmeta() {
            return brojPredmeta;
        }

        /**
         * Sets the value of the brojPredmeta property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setBrojPredmeta(String value) {
            this.brojPredmeta = value;
        }

        /**
         * Gets the value of the datum property.
         *
         * @return
         *     possible object is
         *     {@link Datum }
         *
         */
        public Datum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         *
         * @param value
         *     allowed object is
         *     {@link Datum }
         *
         */
        public void setDatum(Datum value) {
            this.datum = value;
        }

        /**
         * Gets the value of the podnosiocZahteva property.
         *
         * @return
         *     possible object is
         *     {@link PodnosiocZahteva }
         *
         */
        public PodnosiocZahteva getPodnosiocZahteva() {
            return podnosiocZahteva;
        }

        /**
         * Sets the value of the podnosiocZahteva property.
         *
         * @param value
         *     allowed object is
         *     {@link PodnosiocZahteva }
         *
         */
        public void setPodnosiocZahteva(PodnosiocZahteva value) {
            this.podnosiocZahteva = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://localhost:8080/tipovi&gt;Tdatum"&gt;
         *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Datum {

            @XmlValue
            @XmlJavaTypeAdapter(DateAdapter.class)
            protected Date value;
            @XmlAttribute(name = "property")
            @XmlSchemaType(name = "anySimpleType")
            protected String property;
            @XmlAttribute(name = "datatype")
            @XmlSchemaType(name = "anySimpleType")
            protected String datatype;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public Date getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(Date value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                return property;
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="sediste_organa"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivOrgana",
            "sedisteOrgana"
        })
        public static class Organ {

            @XmlElement(name = "naziv_organa", namespace = "http://localhost:8080/obavestenje", required = true)
            protected String nazivOrgana;
            @XmlElement(name = "sediste_organa", namespace = "http://localhost:8080/obavestenje", required = true)
            protected SedisteOrgana sedisteOrgana;

            /**
             * Gets the value of the nazivOrgana property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNazivOrgana() {
                return nazivOrgana;
            }

            /**
             * Sets the value of the nazivOrgana property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNazivOrgana(String value) {
                this.nazivOrgana = value;
            }

            /**
             * Gets the value of the sedisteOrgana property.
             *
             * @return
             *     possible object is
             *     {@link SedisteOrgana }
             *
             */
            public SedisteOrgana getSedisteOrgana() {
                return sedisteOrgana;
            }

            /**
             * Sets the value of the sedisteOrgana property.
             *
             * @param value
             *     allowed object is
             *     {@link SedisteOrgana }
             *
             */
            public void setSedisteOrgana(SedisteOrgana value) {
                this.sedisteOrgana = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attGroup ref="{http://localhost:8080/tipovi}rdfAttributes"/&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class SedisteOrgana {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "property")
                @XmlSchemaType(name = "anySimpleType")
                protected String property;
                @XmlAttribute(name = "datatype")
                @XmlSchemaType(name = "anySimpleType")
                protected String datatype;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the property property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProperty() {
                    return property;
                }

                /**
                 * Sets the value of the property property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProperty(String value) {
                    this.property = value;
                }

                /**
                 * Gets the value of the datatype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatatype() {
                    return datatype;
                }

                /**
                 * Sets the value of the datatype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatatype(String value) {
                    this.datatype = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "naziv",
            "adresa"
        })
        public static class PodnosiocZahteva {

            @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
            protected String ime;
            @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
            protected String prezime;
            @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
            protected String naziv;
            @XmlElement(namespace = "http://localhost:8080/obavestenje", required = true)
            protected String adresa;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdresa(String value) {
                this.adresa = value;
            }

        }

    }

}
