//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 10:52:21 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/resenje", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.administration.services.model;
