//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:38:10 PM CET 
//


package zalbanaodluku;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.zalbanaodluku package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.zalbanaodluku
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zalba }
     * 
     */
    public Zalba createZalba() {
        return new Zalba();
    }

    /**
     * Create an instance of {@link Zalba.PodnosilacZalbe }
     * 
     */
    public Zalba.PodnosilacZalbe createZalbaPodnosilacZalbe() {
        return new Zalba.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link Zalba.Resenje }
     * 
     */
    public Zalba.Resenje createZalbaResenje() {
        return new Zalba.Resenje();
    }

    /**
     * Create an instance of {@link Zalba.DetaljiPredaje }
     * 
     */
    public Zalba.DetaljiPredaje createZalbaDetaljiPredaje() {
        return new Zalba.DetaljiPredaje();
    }

    /**
     * Create an instance of {@link Zalba.InformacijeOPodnosiocuZalbe }
     * 
     */
    public Zalba.InformacijeOPodnosiocuZalbe createZalbaInformacijeOPodnosiocuZalbe() {
        return new Zalba.InformacijeOPodnosiocuZalbe();
    }

}
