//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 04:51:02 PM CET 
//


package zalbanaodluku;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.zalbanaodluku package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.zalbanaodluku
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zalbanaodluku }
     * 
     */
    public Zalbanaodluku createZalbanaodluku() {
        return new Zalbanaodluku();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.PodnosilacZalbe }
     * 
     */
    public Zalbanaodluku.PodnosilacZalbe createZalbanaodlukuPodnosilacZalbe() {
        return new Zalbanaodluku.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.Resenje }
     * 
     */
    public Zalbanaodluku.Resenje createZalbanaodlukuResenje() {
        return new Zalbanaodluku.Resenje();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.DetaljiPredaje }
     * 
     */
    public Zalbanaodluku.DetaljiPredaje createZalbanaodlukuDetaljiPredaje() {
        return new Zalbanaodluku.DetaljiPredaje();
    }

    /**
     * Create an instance of {@link Zalbanaodluku.InformacijeOPodnosiocuZalbe }
     * 
     */
    public Zalbanaodluku.InformacijeOPodnosiocuZalbe createZalbanaodlukuInformacijeOPodnosiocuZalbe() {
        return new Zalbanaodluku.InformacijeOPodnosiocuZalbe();
    }

}
